server:
  port: 8090
spring:
  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://db:5432/root
    url: jdbc:postgresql://localhost:5434/fitness
#    username: root
#    password: root
    username: postgres
    password: kasper
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss.SSS"
    time-zone: "GMT+3"
#  jpa:
#    generate-ddl: false
#    hibernate:
#      ddl-auto: none
#    database: postgresql