#server:
#  port: 8099 #для локальной отладки
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/root
    username: root
    password: root
#    url: jdbc:postgresql://localhost:5434/fitness #для локальной отладки
#    username: postgres
#    password: kasper
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss.SSS"
    time-zone: "GMT+3"
#  jpa:
#    generate-ddl: true
#    hibernate:
#      ddl-auto: none
#    database: postgresql